# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T3tBE6xYMn_0pKRqII-QhH5YW7E8XyGc
"""

s=''
n=int(input())
for i in range(n):
  s=s+'*'
for i in range(n):  
  print(s)

n=int(input())
s='*'*n
for i in range(n):  
  print(s)

n=int(input())
print(('*'*n+'\n')*n)

def foo(s:str, n:int, x):
  return foo(s * n + '\n', n, x-1) if x>0 else s

print(foo('*', 3, 5))

def foo(s:str, n:int, x):
  def rec_in(a,ni):
    if n > 0:
      a += '*'
    else:
      return a
    rec_in(a,n-1)
  return foo(rec_in(s,n) + '\n', n, x-1) if x>0 else s

 print(foo('*',5,2))

import numpy as np
import pandas as pd
normal_sample = np.random.normal(loc=0.0, scale = 1.0, size = 10000)
random_sample = np.random.random( size=10000)
gamma_sample = np.random.gamma(2, size=10000)

df = pd.DataFrame({'normal':normal_sample,
                   'random': random_sample,
                   'gamma': gamma_sample})

df.head()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure()
_ = plt.boxplot(df['normal'], whis = 'range')

import numpy as np
import pandas as pd
import seaborn as sns
anime = pd.read_csv('/anime.csv')



sns.distplot(anime['Source'], bins=25)

